#!/usr/bin/zsh
#
#Check parameter and if filexists
#
KITVPNSCRIPT=~/git/scripts/vpn/kitvpn.ovpn
KITCRED=~/git/scripts/vpn/kitcred
if [ ! -e $KITVPNSCRIPT ] 
then
    echo "No such file..."
    exit
fi


case "$1" in
up)
    echo "starting kit vpn"
    sudo vpnns kit up 10.1.2
    sudo vpnns kit start_vpn $KITVPNSCRIPT $KITCRED ;;
    #sudo vpnns nordvpn run sudo openvpn --config /etc/nordvpn/$1.nordvpn.com.tcp443.ovpn --auth-user-pass /etc/nordvpn/nordvpncred 
down)
    echo "stopping kit vpn"
    sudo vpnns kit stop_vpn
    sudo vpnns kit down
    ;;
run)
    shift
    sudo vpnns kit run "$@";;
esac
