#!/bin/bash

if [[ $UID != 0 ]]; then
    echo "This must be run as root."
    exit 1
fi

function iface_up() {
    NS=$1
    NET=$2
    ip netns add $NS

    ip netns exec $NS ip addr add 127.0.0.1/8 dev lo
    ip netns exec $NS ip link set lo up

    ip link add vpn0 type veth peer name vpn1
    ip link set vpn0 up
    ip link set vpn1 netns $NS up

    ip addr add $NET.1/24 dev vpn0
    ip netns exec $NS ip addr add $NET.2/24 dev vpn1
    ip netns exec $NS ip route add default via $NET.1 dev vpn1

    iptables -A INPUT \! -i vpn0 -s $NET.0/24 -j DROP
    iptables -t nat -A POSTROUTING -s $NET.0/24 -o et+ -j MASQUERADE
    iptables -I FORWARD 1 -s $NET.0/24 -o et+ -j ACCEPT

    sysctl -q net.ipv4.ip_forward=1

    mkdir -p /etc/netns/$NS
    echo 'nameserver 8.8.8.8' > /etc/netns/$NS/resolv.conf

    ip netns exec $NS fping -q www.google.com
}

function iface_down() {
    NS=$1
    rm -rf /etc/netns/$NS
#    NET=$(ip netns exec $NS ip addr show vpn1 | grep -Po 'inet\K[d.]+' | tr "." " " | awk '{print $1"."$2"."$3}' )
    NET=$(ip netns exec $NS  ip addr show vpn1 | grep 'inet' | head -n 1 | awk '{print $2}' | tr "." " " | awk '{print $1"."$2"."$3}')
    sysctl -q net.ipv4.ip_forward=0

    iptables -D INPUT \! -i vpn0 -s $NET.0/24 -j DROP
    iptables -t nat -D POSTROUTING -s $NET.0/24 -o et+ -j MASQUERADE
    iptables -D FORWARD -s $NET.0/24 -o et+ -j ACCEPT

    ip link del vpn0
    ip netns delete $NS
}

function run() {
    NS=$1
    shift
    exec sudo ip netns exec $NS "$@"
}

function start_vpn() {
    NS=$1
    CFG=$2
    sudo ip netns exec $NS openvpn --config /etc/nordvpn/$CFG.nordvpn.com.tcp443.ovpn --auth-user-pass /etc/nordvpn/nordvpncred &

    while ! sudo ip netns exec $NS ip a show dev tun0 up; do
        sleep .5
    done
}

function stop_vpn() {
    sudo killall openvpn
}

case "$2" in
    up)
        iface_up $1 $3;;
    down)
        iface_down $1;;
    run)
        NS=$1
        shift
        shift
        run $NS "$@" ;;
    start_vpn)
        start_vpn $1 $3;;
    stop_vpn)
        stop_vpn $1;;
    *)
        echo "Syntax: $0 up|down|run|start_vpn"
        echo "vpnns <netns> up <XXX.XXX.XXX>"
        echo "vpnns <netns> down"
        echo "vpnns <netns> start_vpn <config_file_path>"
        echo "vpnns <netns> run <command>"
        exit 1
        ;;
esac
